name = "tanager-edge-api"
main = "worker/src/worker1.ts"
compatibility_date = "2026-05-04"
compatibility_flags = ["nodejs_compat"]

[vars]
AZURE_FUNCTION_URL = "https://resume-dev-function.azurewebsites.net"

routes = [
    "api.tanager-solutions.com/api/*"
]

[[kv_namespaces]]
binding = "VISITORS_KV"
id = "fc913d7a648740a8bb0d130e64f010f3"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
