name = "tanager-edge-api"
main = "worker.ts"
compatibility_date = "2026-05-04"

[vars]
AZURE_FUNCTION_URL = "https://resume-dev-function.azurewebsites.net"

routes = [
  "api.tanager-solutions.com/*"
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
