name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest
    outputs:
      function_app_name: ${{ steps.tf_outputs.outputs.function_app_name }}
      resource_group: ${{ steps.tf_outputs.outputs.resource_group }}
      storage: ${{ steps.tf_outputs.outputs.storage }}

    permissions:
      id-token: write
      contents: read
    
    env:
      TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
      TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
      TF_VAR_location: ${{ secrets.LOCATION }}

    defaults:
      run:
        working-directory: ./infra
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        if: github.ref == 'refs/heads/main'

      - name: Capture Terraform Outputs
        id: tf_outputs
        run: |
          #Function App Name
          echo "AZURE_FUNCTIONAPP_NAME=$(terraform output -raw function_app_name)" >> $GITHUB_OUTPUT

          #Resource Group
          echo "AZURE_RESOURCE_GROUP=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT

          #Storage Account Name
          echo "STORAGE=$(terraform output -raw storage_account_name)" >> $GITHUB_OUTPUT
        
  deploy_frontend:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.FRONTEND_DEPLOYMENT_TOKEN }}
          action: "upload"
          app_location: "frontend"
          output_location: "frontend"

  build_and_deploy_function:
    needs: terraform
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      id-token: write
      contents: read

    env:
      AZURE_FUNCTIONAPP_NAME: ${{ needs.terraform.outputs.AZURE_FUNCTIONAPP_NAME }}
      AZURE_RESOURCE_GROUP: ${{ needs.terraform.outputs.AZURE_RESOURCE_GROUP }}
      STORAGE: ${{ needs.terraform.outputs.STORAGE }}
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/ResumeCounter.Functions'
      DOTNET_VERSION: '8.0.x'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet publish --configuration Release --output ./output --self-contained false
        popd

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}