name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: TF_LOG=INFO terraform plan -input=false
        env:
          TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
          TF_VAR_subscription_id: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
          TF_VAR_location: ${{ secrets.LOCATION }}
          TF_VAR_repo_url: ${{ secrets.REPO_URL }}
          TF_VAR_repo_token: ${{ secrets.REPO_TOKEN }}
          TF_VAR_cosmosdb_connection_string: ${{ secrets.COSMOS_CONNECTION_STRING }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
          TF_VAR_location: ${{ secrets.LOCATION }}
          TF_VAR_repo_url: ${{ secrets.REPO_URL }}
          TF_VAR_repo_token: ${{ secrets.REPO_TOKEN }}
          TF_VAR_cosmosdb_connection_string: ${{ secrets.COSMOS_CONNECTION_STRING }}
        if: github.ref == 'refs/heads/main'
  deploy_frontend:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.FRONTEND_DEPLOYMENT_TOKEN }}
          action: "upload"
          app_location: "frontend"
          output_location: "frontend"

  deploy_function:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ZIP to Azure Function
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --src ./backend/ResumeCounter.Functions/function.zip

      - name: Debug
        run: | 
          az functionapp show --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}